---
# tasks file for patching


- include_tasks: update_version_{{ ansible_distribution_major_version }}.yaml



#- name: Update OS RHEL/OEL 7 Version
#  import_tasks: update_version_7.yaml
#  when: ansible_distribution_major_version == "7"




#- name: Update OS RHEL/OEL 6 Version
#  import_tasks: update_version_6.yaml
#  when: ansible_distribution_major_version == "6"




#- name: Update OS RHEL/OEL 5 Version
#  import_tasks: update_version_5.yaml
#  when: ansible_distribution_major_version == "5"


...

