# checkdiskspaceall.yml
---

- hosts: all
# vars_files: vault.yml
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    percentage: 0.84
  tasks:
     - name: Collect only facts about hardware
       setup:
         gather_subset:
           - 'hardware'

     - name: Test for available disk space
       setup: filter=ansible_mounts

     - name: Check Template
       template:
         src: mounts_info.j2
         dest: mount_info.txt

     - name: Block and rescue for boot
       block:
         - name: "Ensure that free space on {{ mountname }} is greater than 20%"
           assert:
             that:
               - mount.size_available > mount.size_total|float * per
             msg: Disk space has reached '{{ per * 100 }}'% threshold
           vars:
             - per: '{{ percentage }}'
             - mount: "{{ ansible_mounts | selectattr('mount','equalto',item) | list | first  }}"
           with_items:
             - /boot
           register: boot_free

       rescue:
         - name: Stop Service
           service: name=httpd state=stopped
           when: boot_free is defined and boot_free is failed
...
